---
title: "Ax–Grothendieck Theorem"
date: "2025-12-07"
categories: [Interesting Facts, Advanced Topics]
---

# Introduction

We all know from basic linear algebra that injective endomorphisms of a finite-dimensional vector space are also surjective. The same holds for finite sets. Over algebraically closed fields, there is an analogous result:

::: {#thm-ax-special}
## Special case of Ax–Grothendieck Theorem

Let $k$ be an algebraically closed field, $n\in \mathbb{N}$, and $f_1,\dots,f_n\in k[x_1,\dots ,x_n]$. If the map
$$
F:k^n \rightarrow k^n, \qquad F(\underline{x})=(f_1(\underline{x}),\dots, f_n(\underline{x}))
$$
is injective, then it is surjective.
:::

We will talk about an analogous and more general statement about schemes later on.

Let us comment briefly on the hypotheses. Injectivity is the correct assumption for $F$: the map $z\mapsto z^2$ is surjective but not injective on $\mathbb{C}$. Furthermore, the result is generally false for non-algebraically closed fields; for example, $x \mapsto x^3$ is injective but not surjective on $\mathbb{Q}$.

As a sanity check, let's verify the result for $n=1$. Consider a polynomial $f\in k[x]$ such that the map $x\mapsto f(x)$ is injective; then $f$ can have at most one root. Since $k$ is algebraically closed, it follows that $f=ax+b$ with $a\neq 0$ (otherwise the map would not be injective). Hence $f$ is surjective.

Moreover, the theorem is easy to prove when $k=\overline{\mathbb{F}}_p$.

::: {.proof}
#### For $k=\overline{\mathbb{F}}_p$

Let $\underline z:=(z_1,\dots, z_n)\in k^n$ and let $L$ be the subfield of $k$ generated by the coefficients of the polynomials defining $F$ and by the $z_i$'s. The field $L$ is a finite extension of $\mathbb{F}_p$, hence a finite set. The restriction $F:L^n\rightarrow L^n$ is well-defined and injective; since $L^n$ is finite it is also surjective. Therefore, $\underline z$ lies in the image of $F$, proving the claim.
:::

---

# Proof of the theorem

We start by proving two lemmas and then proceed with the proof of [Theorem @thm-ax-special].

::: {#lem-criterion-injectivity}
## Lemma

The map $F$ is injective if and only if there exist $q_{i,j}\in k[x_1,\dots,x_n,y_1,\dots,y_n]$ and integers $k_j>0$ such that, defining
$$
g_i(x_1,\dots, x_n,y_1,\dots,y_n)
:=f_i(x_1,\dots , x_n)-f_i(y_1,\dots,y_n),
$$
for all $j$ we have the identity
$$
\sum_{i=1}^n g_i\cdot q_{i,j}=(x_j-y_j)^{k_j}
$$ {#eq-g-criterion}
:::

::: {.proof}

Consider the ideal $I=(g_1,\dots, g_n)$. The map $F$ is injective if and only if all the zeros of $I$ are of the form $(\underline{x},\underline{x})$ for $\underline{x}\in k^n$. This is the case if and only if the zeros of $I$ are a subset of the zeros of $J=(x_1-y_1,\dots,x_n-y_n)$, i.e. if and only if $\mathrm{V}(I) \subseteq \mathrm{V}(J)$. By the [Hilbert Nullstellensatz](https://en.wikipedia.org/wiki/Hilbert%27s_Nullstellensatz), this holds if and only if $J \subseteq \sqrt I$; hence $(x_j-y_j)\in \sqrt{I}$.
:::

::: {#lem-no-preimage}
## Lemma

Let $\underline{z}\in k^n$. Then $\underline z$ is not in the image of $F$ if and only if there exist $r_1,\dots ,r_n\in k[x_1,\dots ,x_n]$ such that
$$
\sum_{i=1}^n r_i\cdot (f_i-z_i)=1.
$$ {#eq-r-criterion}
:::

::: {.proof}

The element $\underline{z}$ is not in the image of $F$ if and only if the ideal $I=(f_1-z_1,\dots,f_n-z_n)$ has no zeros, equivalently $1\in I$ (again by Nullstellensatz).
:::

Now we are ready to prove the theorem.

::: {.proof}
#### Of [Theorem @thm-ax-special]

Suppose $\underline{z}\in k^n$ is not in the image of $F$. Let $A$ be the $\mathbb{Z}$-algebra generated by:

- the coefficients of the $f_i$'s defining $F$;
- the $z_i$'s;
- the coefficients of the $q_{i,j}$ as in [Lemma @lem-criterion-injectivity];
- the coefficients of the $r_i$ as in [Lemma @lem-no-preimage].

Since finitely many coefficients are involved, $A$ is of finite type over $\mathbb{Z}$. Moreover, the restriction $F:A^n \rightarrow A^n$ is still injective. Furthermore, we have the following identities in $A[x_1,\dots,x_n,y_1,\dots,y_n]$ given respectively by [Lemma @lem-criterion-injectivity] and [Lemma @lem-no-preimage]:
$$
\sum_{i=1}^n g_i\cdot q_{i,j}=(x_j-y_j)^{k_j}
$$ {#eq-criterion-1}

$$
\sum_{i=1}^n r_i\cdot (f_i-z_i)=1
$$ {#eq-criterion-2}

Now pick a maximal ideal $m$ in $A$. The field $A/m$ is finite by the following claim.

::: {.claim}

<a id="clm-nullstellensatz-Z"></a>

**Claim:**
Let $B$ be an algebra of finite type over $\mathbb{Z}$. If $m$ is a maximal ideal of $B$, then $B/m$ is a finite field.

:::

Assuming the claim, set $L=A/m$ and note that the reduction $\overline{F}:L^n\rightarrow L^n$ of $F$ modulo $m$ is injective. Indeed, consider $\underline x,\underline y\in L^n$ such that $\overline{F}(\underline x)=\overline{F}(\underline y)$. By evaluating [Equation @eq-criterion-1] at $(\underline x,\underline y)$ we obtain $\underline x=\underline y$ in $L^n$, since $\overline g_i(\underline x, \underline y)=0$ for all $i$.

Since $L^n$ is finite and $\overline{F}$ is injective, $\overline F$ is surjective. However, reducing $\underline{z}$ modulo $m$ and evaluating [Equation @eq-criterion-2] at a preimage of that reduction under $\overline F$ yields a contradiction. Hence, up to proving the claim, we have established [Theorem @thm-ax-special].

::: {.proof}

#### of the Claim

Consider two cases:

- If $m\cap \mathbb{Z}=p \mathbb{Z}$, then $B/m$ is an algebra of finite type over $\mathbb{F}_p$; by [Zariski's lemma](https://en.wikipedia.org/wiki/Zariski%27s_lemma) $B/m$ is a finite extension of $\mathbb{F}_p$, hence finite.
- If $m\cap \mathbb{Z}=0$, then in the tower $\mathbb{Z} \subset \mathbb{Q} \subset B/m$, we see that $B/m$ is of finite type over $\mathbb{Q}$, hence is finite over $\mathbb{Q}$ by Zariski's lemma. [Artin–Tate's lemma](https://en.wikipedia.org/wiki/Artin%E2%80%93Tate_lemma) then implies that $\mathbb{Q}$ would be of finite type over $\mathbb{Z}$, a contradiction.

:::

:::

---

# Generalization to schemes

Note that the map $F$ considered in [Theorem @thm-ax-special] can be seen as the map induced on closed points by a morphism of $k$-schemes $\mathbb{A}^n_k\rightarrow \mathbb{A}^n_k$. This leads to the following question:

::: {#qst-example}
**Question:**

Let $k$ be an algebraically closed field and $X$ a scheme of finite type over $k$. If $f:X\rightarrow X$ is a $k$-endomorphism injective on $k$-points, is it surjective on all points?

:::

The finite-type assumption is necessary: the map induced by
$$
k[X_1,\dots, X_n,\dots]\to k[X_1,\dots, X_n,\dots]
$$
sending $X_1\mapsto 0$ and $X_i\mapsto X_{i-1}$ for $i>1$ is injective but not surjective.

The answer is positive, and it follows (not trivially) from the following theorem.

::: {#thm-ax-groth}
## Ax–Grothendieck Theorem

Let $S$ be a scheme and let $X$ be a scheme of finite type over $S$. Any injective $S$-endomorphism $f:X\rightarrow X$ is bijective.
:::

Moreover, if $X$ is reduced and $k$ is an algebraically closed field of characteristic $0$, then an injective endomorphism on $k$-points is in fact an isomorphism (not merely a bijection). This is not trivial since we have bijective morphisms of schemes that are not isomorphisms (for example the one induced by $k[t^2,t^3]\rightarrow k[t]$). A reference for this is Lemma 1 of [this article](https://www.jstor.org/stable/4097654).

We will not give a proof of [Theorem @thm-ax-groth]; see J. Ax's paper [Injective endomorphisms of varieties and schemes](https://projecteuclid.org/journals/pacific-journal-of-mathematics/volume-31/issue-1/Injective-endomorphisms-of-varieties-and-schemes/pjm/1102978046.full), or Grothendieck's version in [EGA IV$_3$, Proposition 10.4.11](https://www.numdam.org/item/PMIHES_1966__28__5_0/) for a complete proof.

Let us explain why [Theorem @thm-ax-groth] implies that injectivity on $k$-points gives surjectivity on all points.

The first ingredient is Chevalley's theorem on constructible sets (see Hartshorne, Ex. II.3.19).

::: {#thm-chevalley}
## Chevalley's theorem

Let $f:X\to Y$ be a finite type morphism between noetherian schemes. If $Z \subseteq X$ is a constructible subset (i.e. a finite union of locally closed subsets), then $f(Z)$ is constructible.
:::

The following lemma explains why [Theorem @thm-ax-groth] implies [Theorem @thm-ax-special].

::: {#lem-universally-injective}
## Lemma

Let $X, Y$ be schemes of finite type over an algebraically closed field $k$. Let $f:X\to Y$ be a morphism whose restriction to $k$-points
$$
f: X(k)\to Y(k)
$$
is injective. Then $f$ is universally injective.
:::

Assuming this lemma, consider a morphism $f:\mathbb{A}^n_k\to \mathbb{A}^n_k$ over $k$ which is injective on closed points (which are exactly the $k$-points, since $k$ is algebraically closed). Then in particular $f$ is injective on all points. From [Theorem @thm-ax-groth] we get the surjectivity of $f$ on all points (answering the question raised before) and in particular also surjectivity on closed points, since only closed points are sent to closed points. In particular, we obtain [Theorem @thm-ax-special].

::: {.proof}
#### Of [Lemma @lem-universally-injective]

Observe that the diagonal $\Delta_f:X\to X\times_Y X$ is of finite type. Indeed, it is locally of finite type because $X\to \mathrm{Spec}(k)$ is locally of finite type (and $\Delta_f$ can be seen as the first factor of this map), and it is quasi-compact because $X$ is noetherian (being of finite type over $k$).

Moreover, the diagonal $\Delta_f$ is surjective on $k$-points. Indeed, for any $k$-point of $X\times_Y X$ given by a morphism
$$
\psi: \mathrm{Spec}(k)\to X\times_Y X
$$
we can consider the diagram

<!-- https://q.uiver.app/#q=WzAsNSxbMCwwLCJcXG1hdGhybXtTcGVjfShrKSJdLFsxLDEsIlhcXHRpbWVzX1kgWCJdLFsyLDEsIlgiXSxbMSwyLCJYIl0sWzIsMiwiWSJdLFsxLDJdLFswLDIsIlxccGhpXzIiLDAseyJjdXJ2ZSI6LTN9XSxbMSw0LCIiLDIseyJzdHlsZSI6eyJuYW1lIjoiY29ybmVyIn19XSxbMiw0XSxbMyw0XSxbMSwzXSxbMCwzLCJcXHBoaV8xIiwyLHsiY3VydmUiOjN9XSxbMCwxLCJcXHBzaSIsMl1d -->
<iframe class="quiver-embed" src="https://q.uiver.app/#q=WzAsNSxbMCwwLCJcXG1hdGhybXtTcGVjfShrKSJdLFsxLDEsIlhcXHRpbWVzX1kgWCJdLFsyLDEsIlgiXSxbMSwyLCJYIl0sWzIsMiwiWSJdLFsxLDJdLFswLDIsIlxccGhpXzIiLDAseyJjdXJ2ZSI6LTN9XSxbMSw0LCIiLDIseyJzdHlsZSI6eyJuYW1lIjoiY29ybmVyIn19XSxbMiw0XSxbMyw0XSxbMSwzXSxbMCwzLCJcXHBoaV8xIiwyLHsiY3VydmUiOjN9XSxbMCwxLCJcXHBzaSIsMl1d&embed" width="400" height="400" style="border-radius: 8px; border: none;"></iframe>

and by injectivity of the morphism $X\to Y$ we obtain $\phi_1=\phi_2$ as maps of topological spaces. They are also the same on the structure sheaf, because $k$ is algebraically closed. Therefore, $\phi_1=\phi_2$, which means that $\psi$ factorizes through the diagonal $\Delta_f$.

Furthermore, $X\times _Y X$ is a [Jacobson](https://stacks.math.columbia.edu/tag/005T) scheme (i.e. its underlying topological space is Jacobson) because it is of finite type over $k$, and $k$ is Jacobson. By [Theorem @thm-chevalley] the set $\Delta_f(X)$ is constructible. Consider $Z:=(X\times_Y X)\smallsetminus \Delta_f(X)$. This is constructible and every closed point of $X\times_Y X$ lies inside $\Delta_f(X)$ (by surjectivity of $\Delta_f$ on closed points). Since every nonempty constructible subset in a Jacobson scheme contains a closed point, it follows that $Z=\emptyset$. Therefore, $\Delta_f$ is surjective on all points.

Now we prove that the surjectivity of $\Delta_f$ implies the universal injectivity of $f$. Indeed, consider any $g: Z\to Y$ and the diagonal
$$
\Delta: X\times_Y Z\to (X\times_Y Z)\times_Z(X\times_Y Z)
$$
of the base change. This diagonal map $\Delta$ is surjective because it is the base change of $\Delta_f$, which is surjective. Thus, we are reduced to proving that surjectivity of $\Delta_f$ implies injectivity of $f$ (the same will then hold for any base change).

Consider $x_1,x_2\in X$ with $f(x_1)=f(x_2)=:y$. We can find a field $L$ such that the following diagram commutes:

<!-- https://q.uiver.app/#q=WzAsNCxbMCwxLCJrKHkpIl0sWzEsMCwiayh4XzEpIl0sWzEsMiwiayh4XzIpIl0sWzIsMSwiTCJdLFswLDFdLFswLDJdLFsyLDNdLFsxLDNdXQ== -->
<iframe class="quiver-embed" src="https://q.uiver.app/#q=WzAsNCxbMCwxLCJrKHkpIl0sWzEsMCwiayh4XzEpIl0sWzEsMiwiayh4XzIpIl0sWzIsMSwiTCJdLFswLDFdLFswLDJdLFsyLDNdLFsxLDNdXQ==&embed" width="400" height="400" style="border-radius: 8px; border: none;"></iframe>

We get the following commutative diagram:
<!-- https://q.uiver.app/#q=WzAsNSxbMCwwLCJcXG1hdGhybXtTcGVjfShMKSJdLFsxLDEsIlhcXHRpbWVzX1kgWCJdLFsxLDIsIlgiXSxbMiwxLCJYIl0sWzIsMiwiWSJdLFswLDEsIlxcZXhpc3RzISBcXGVwc2lsb24iLDEseyJzdHlsZSI6eyJib2R5Ijp7Im5hbWUiOiJkb3R0ZWQifX19XSxbMSwyXSxbMSwzXSxbMyw0XSxbMiw0XSxbMCwyLCJ4XzEiLDIseyJjdXJ2ZSI6M31dLFswLDMsInhfMiIsMCx7ImN1cnZlIjotM31dLFsxLDQsIiIsMCx7InN0eWxlIjp7Im5hbWUiOiJjb3JuZXIifX1dXQ== -->
<iframe class="quiver-embed" src="https://q.uiver.app/#q=WzAsNSxbMCwwLCJcXG1hdGhybXtTcGVjfShMKSJdLFsxLDEsIlhcXHRpbWVzX1kgWCJdLFsxLDIsIlgiXSxbMiwxLCJYIl0sWzIsMiwiWSJdLFswLDEsIlxcZXhpc3RzISBcXGVwc2lsb24iLDEseyJzdHlsZSI6eyJib2R5Ijp7Im5hbWUiOiJkb3R0ZWQifX19XSxbMSwyXSxbMSwzXSxbMyw0XSxbMiw0XSxbMCwyLCJ4XzEiLDIseyJjdXJ2ZSI6M31dLFswLDMsInhfMiIsMCx7ImN1cnZlIjotM31dLFsxLDQsIiIsMCx7InN0eWxlIjp7Im5hbWUiOiJjb3JuZXIifX1dXQ==&embed" width="400" height="400" style="border-radius: 8px; border: none;"></iframe>

By surjectivity of $\Delta_f$ we can find $x\in X$ such that $\Delta_f(x)$ is the image of $\epsilon$, hence we get $x_1=x_2$. This shows that $f$ is injective, and therefore universally injective.
:::

Note that the complex-geometric picture does not match the algebraic one. For example, there are holomorphic maps $\mathbb{C}^n\rightarrow \mathbb{C}^n$ that are injective but not surjective. However, this cannot happen for $n=1$, as one can show that all holomorphic injective maps $f: \mathbb{C}\rightarrow \mathbb{C}$ are of the form $f=ax+b$; see the [Casorati–Weierstrass theorem](https://en.wikipedia.org/wiki/Casorati%E2%80%93Weierstrass_theorem).

---

# Conclusion

To conclude, we point your attention to the fact that this theorem is linked to a famous conjecture, namely the [Jacobian conjecture](https://en.wikipedia.org/wiki/Jacobian_conjecture).

::: {#cnj-jacobian}
## Jacobian conjecture

Let $k$ be a field of characteristic $0$ and let $F: k^n\to k^n$ be a polynomial mapping. If the Jacobian determinant $J_F$ is invertible, then $F$ is an isomorphism.
:::

Over an algebraically closed field of characteristic $0$, the fact that the bijection in [Theorem @thm-ax-groth] becomes an isomorphism shows that, to prove the Jacobian conjecture for $\mathbb{A}^n_k$, it suffices to show that a map
$$
F:\mathbb{A}^n_k\rightarrow \mathbb{A}^n_k
$$
with invertible Jacobian determinant is injective.

---

I would like to thank my friend who suggested this topic to me and helped me write this post.

---

# References

This post was mainly inspired by [this post](https://terrytao.wordpress.com/2009/03/07/infinite-fields-finite-fields-and-the-ax-grothendieck-theorem/comment-page-1/) from Terence Tao's blog. Other references are cited in the text when used.

